<!DOCTYPE html>
<html lang="pl">
<head>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css"
          integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <meta charset="utf-8">
    <title>Homework</title>
</head>
<body>

<h4>Homework <span class="badge badge-secondary">5</span></h4>
<span class="badge badge-primary">${name}</span>
<span class="badge badge-secondary">${team}</span>
<span class="badge badge-success">>${date}</span>

<#include "footer.ftlh"/>
</body>
</html>